name: Deploy Next.js site to Pages

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: duongthuan-portfolio

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check file location
        run: ls

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: ./duongthuan-portfolio

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ./duongthuan-portfolio/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-

      - name: Install dependencies
        run: |
          npm ci

      - name: Build with Next.js
        run: npm run build

      - name: Test with Next.js
        run: npm test
